# Generated by Django 4.0.8 on 2023-01-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='productcondition',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productrate',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productstock',
            old_name='item',
            new_name='product',
        ),
    ]
