# Generated by Django 4.0.8 on 2023-01-18 13:40

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_item_type_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_directory_path),
        ),
    ]
