# Generated by Django 4.0.8 on 2023-01-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_reviews',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
