# Generated by Django 4.0.8 on 2023-01-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_total_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_reviews',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
