# Generated by Django 4.0.8 on 2023-01-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_productimage_image'),
        ('products', '0014_productdamage_delete_productdemurrage'),
    ]

    operations = [
    ]
