# Generated by Django 4.0.8 on 2023-02-02 08:49

import apps.products.models
import apps.utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_directory_path, validators=[apps.utilities.validators.validate_product_image_size]),
        ),
    ]
