# Generated by Django 4.0.8 on 2023-02-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rename_size_productsize_product_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
