# Generated by Django 4.0.8 on 2023-02-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_delete_productstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCondition',
        ),
    ]
