# Generated by Django 4.0.8 on 2023-02-08 10:53

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_delete_productcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_directory_path),
        ),
    ]
