# Generated by Django 4.0.8 on 2023-02-18 08:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
