# Generated by Django 4.0.8 on 2023-02-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security Deposit'),
        ),
    ]
