# Generated by Django 4.0.8 on 2023-02-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_delete_govelowork_delete_homepage'),
        ('products', '0031_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.currency'),
        ),
    ]
