# Generated by Django 4.0.8 on 2023-02-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productdeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deposit',
        ),
    ]
