# Generated by Django 4.0.8 on 2023-03-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_product_deposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-id']},
        ),
    ]
