# Generated by Django 4.0.8 on 2023-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('SHIPPING', 'Shipping'), ('BILLING', 'Billing')], max_length=100, null=True, unique=True, verbose_name='Address Type Name')),
            ],
            options={
                'verbose_name_plural': 'Address Types',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Types',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Contact Type Name')),
            ],
            options={
                'verbose_name_plural': 'Contact Types',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Currency Name')),
                ('code', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('INR', 'INR'), ('CNY', 'CNY'), ('BDT', 'BDT'), ('RUB', 'RUB'), ('BRL', 'BRL'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('KRW', 'KRW')], max_length=20, null=True, unique=True)),
                ('symbol', models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€'), ('JPY', '¥'), ('INR', '₹'), ('CNY', '¥'), ('BDT', '৳'), ('RUB', '₽'), ('BRL', 'R$'), ('GBP', '£'), ('AUD', '$'), ('CAD', '$'), ('KRW', '₩')], max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Language Name')),
                ('code', models.CharField(blank=True, choices=[('EN', 'en'), ('ES', 'es'), ('FR', 'fr'), ('DE', 'de'), ('IT', 'it'), ('PT', 'pt'), ('RU', 'ru'), ('AR', 'ar'), ('BN', 'bn'), ('Hi', 'hi'), ('JA', 'ja'), ('KO', 'ko')], max_length=10, null=True, unique=True, verbose_name='Language Code')),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Nomination Types',
            },
        ),
        migrations.CreateModel(
            name='NomintaionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nomination Name')),
            ],
            options={
                'verbose_name_plural': 'Nomination Types',
            },
        ),
        migrations.CreateModel(
            name='ProductRateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Product Rate Type Name')),
            ],
            options={
                'verbose_name_plural': 'Product Rate Types',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Product Type Name')),
            ],
            options={
                'verbose_name_plural': 'Product Types',
            },
        ),
    ]
