# Generated by Django 4.0.8 on 2023-01-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NomintaionType',
            new_name='NominationType',
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name_plural': 'Nominations'},
        ),
    ]
