# Generated by Django 4.0.8 on 2023-01-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_rename_nomintaiontype_nominationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationtype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nomination Type'),
        ),
    ]
