# Generated by Django 4.0.8 on 2023-01-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_alter_contact_options_nomination_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Address Type Name'),
        ),
    ]
