# Generated by Django 4.0.8 on 2023-01-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_remove_contact_contact_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='doner',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='nominee',
        ),
        migrations.AddField(
            model_name='nomination',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
