# Generated by Django 4.0.8 on 2023-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_remove_nomination_doner_remove_nomination_nominee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoVeloWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/goveloworks/')),
            ],
            options={
                'verbose_name_plural': 'Go Velo Works',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/logo/', verbose_name='Site Logo')),
                ('site_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Site Video')),
            ],
        ),
    ]
