# Generated by Django 4.0.8 on 2023-02-05 13:30

import apps.utilities.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_govelowork_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govelowork',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/goveloworks/', validators=[apps.utilities.validators.validate_site_icon_size]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])], verbose_name='Site Video'),
        ),
    ]
