# Generated by Django 4.0.8 on 2023-02-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_alter_govelowork_icon_alter_homepage_site_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoVeloWork',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
