# Generated by Django 4.0.8 on 2023-02-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_delete_govelowork_delete_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, choices=[('$', 'USD'), ('€', 'EUR')], max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, choices=[('USD', '$'), ('EUR', '€')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, choices=[('EN', 'en'), ('ES', 'es')], max_length=10, null=True, unique=True, verbose_name='Language Code'),
        ),
    ]
