# Generated by Django 3.2.15 on 2023-04-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_eventtype_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
