# Generated by Django 3.2.15 on 2023-04-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='rental_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
