# Generated by Django 4.0.8 on 2023-01-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='product',
        ),
    ]
