# Generated by Django 4.0.8 on 2023-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_padi_at_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
