# Generated by Django 4.0.8 on 2023-01-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_order_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='area_code',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
