# Generated by Django 4.0.8 on 2023-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_paymentinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='payment_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
