# Generated by Django 4.0.8 on 2023-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_paymentinformation_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Delivered', 'Delivered'), ('Past', 'Past'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=50, null=True),
        ),
    ]
