# Generated by Django 4.0.8 on 2023-02-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_refund_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='duration',
        ),
        migrations.AddField(
            model_name='order',
            name='order_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
