# Generated by Django 4.0.8 on 2023-02-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_duration_order_order_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_duration',
            new_name='duration',
        ),
    ]
