# Generated by Django 4.0.8 on 2023-02-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_rename_order_duration_order_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
