# Generated by Django 3.2.15 on 2023-04-11 08:22

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_rental_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rental_number',
            field=models.CharField(blank=True, default=apps.orders.models.rental_numbers, max_length=50, null=True),
        ),
    ]
