# Generated by Django 4.0.8 on 2023-01-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policies'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name_plural': 'Terms And Conditions'},
        ),
    ]
