# Generated by Django 4.0.8 on 2023-01-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aboutus_description_aboutus_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
