# Generated by Django 4.0.8 on 2023-01-23 09:10

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_aboutus_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='description',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='description',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
    ]
