# Generated by Django 4.0.8 on 2023-01-26 15:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_privacypolicy_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
