# Generated by Django 4.0.8 on 2023-02-05 13:59

import apps.utilities.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aboutus_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoVeloWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/goveloworks/', validators=[apps.utilities.validators.validate_site_icon_size])),
            ],
            options={
                'verbose_name_plural': 'Go Velo Works',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/logo/', verbose_name='Site Logo')),
                ('site_video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])], verbose_name='Site Video')),
            ],
            options={
                'verbose_name_plural': 'Home Page content',
            },
        ),
    ]
