# Generated by Django 4.0.8 on 2023-02-05 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_govelowork_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/site/logo/', verbose_name='Site Logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])], verbose_name='Site Video'),
        ),
    ]
