# Generated by Django 4.0.8 on 2023-02-05 14:06

import apps.utilities.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_homepage_site_logo_alter_homepage_site_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govelowork',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='govelowork',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/goveloworks/', validators=[apps.utilities.validators.validate_site_icon_size]),
        ),
        migrations.AlterField(
            model_name='govelowork',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_logo',
            field=models.ImageField(null=True, upload_to='images/site/logo/', verbose_name='Site Logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site_video',
            field=models.FileField(null=True, upload_to='videos/site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])], verbose_name='Site Video'),
        ),
    ]
