# Generated by Django 4.0.8 on 2023-02-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_govelowork_description_alter_govelowork_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home Page contents'},
        ),
    ]
