# Generated by Django 4.0.8 on 2023-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_legal_entity_alter_shop_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='openening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
