# Generated by Django 4.0.8 on 2023-01-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_rename_shop_cover_shop_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='cover_image',
        ),
    ]
