# Generated by Django 4.0.8 on 2023-01-31 07:25

import apps.shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_remove_shop_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='openening_time',
            new_name='opening_time',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.shops.models.shop_cover_directory_path),
        ),
    ]
