# Generated by Django 4.0.8 on 2023-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_rename_openening_time_shop_opening_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
