# Generated by Django 4.0.8 on 2023-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_shop_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
