# Generated by Django 4.0.8 on 2023-02-02 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_alter_shop_shop_cover_alter_shop_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
