# Generated by Django 4.0.8 on 2023-02-02 11:01

import apps.shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_rename_shop_rating_shop_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.shops.models.shop_cover_directory_path),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.shops.models.shop_directory_path),
        ),
    ]
