# Generated by Django 4.0.8 on 2023-02-06 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_shop_is_verified_shopverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopverification',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/verification/id_back', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='shopverification',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/verification/id_front', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
