# Generated by Django 4.0.8 on 2023-02-07 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_alter_shopverification_id_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopverification',
            name='id_back_image',
            field=models.ImageField(null=True, upload_to='shops/verification/id_back', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='shopverification',
            name='id_front_image',
            field=models.ImageField(null=True, upload_to='shops/verification/id_front', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='shopverification',
            name='owner_image',
            field=models.ImageField(null=True, upload_to='shops/verification/owner'),
        ),
    ]
