# Generated by Django 4.0.8 on 2023-02-19 11:48

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_alter_shopverification_id_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='terms_and_condition',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
