# Generated by Django 4.0.8 on 2023-02-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_alter_shop_terms_and_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['id']},
        ),
    ]
