# Generated by Django 3.2.15 on 2023-03-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_auto_20230306_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
