# Generated by Django 3.2.15 on 2023-03-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0023_auto_20230306_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='pick_up_location',
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
