# Generated by Django 4.0.8 on 2023-02-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_connection_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.connection'),
        ),
    ]
